### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by miho** [turpid-monkey/modelgen#5]
Calling 

```java
        Model model = new Model();
        model.init(MethodNode.class, ClassNode.class);
```

with:

```java
public interface ClassNode {
    @Containment MethodNode getMethod();
}

public interface MethodNode extends Contained<ClassNode>{

}
```

results in:

```
Exception in thread "main" java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at org.mism.modelgen.Property.init(Property.java:31)
	at org.mism.modelgen.Type.initProperties(Type.java:154)
	at org.mism.modelgen.Type.init(Type.java:82)
	at org.mism.modelgen.Model.initType(Model.java:44)
	at org.mism.modelgen.Model.init(Model.java:25)
```

**Comment by turpid-monkey** [comment]
Fixed this specific issue, but the generated code might not be fully consistent with the semantic meaning of containment and has to be reviewed.
